// src/components/revolution/Canvas2D.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from "vue";
import type { CurveDefinition, ComputedRegion } from "@/utils/mathEngine";
import { sampleCurve } from "@/utils/mathEngine";

const props = defineProps<{
  curves: CurveDefinition[];
  region: ComputedRegion | null;
  xMin: number;
  xMax: number;
  axis: "x" | "y";
  axisValue: number;
}>();

const canvasRef = ref<HTMLCanvasElement | null>(null);
const containerRef = ref<HTMLDivElement | null>(null);
const canvasWidth = ref(600);
const canvasHeight = ref(400);

// View transform state
const viewOffset = ref({ x: 0, y: 0 });
const viewScale = ref(1);

// Interaction state (pan only; wheel zoom remains disabled)
const isDragging = ref(false);
const lastMousePos = ref({ x: 0, y: 0 });

let pinchStartDistance = 0;
let pinchStartScale = 1;
let lastTouchCenter: { x: number; y: number } | null = null;

const defaultCurveColors = [
  "#4f6ef7",
  "#e74c8b",
  "#2ecc71",
  "#f0a500",
  "#9b59b6",
  "#1abc9c",
  "#e67e22",
  "#3498db",
];

// Coordinate transform: math coords -> canvas pixel coords
function mathToCanvas(
  mx: number,
  my: number,
  padding: number,
  xRange: [number, number],
  yRange: [number, number]
): { cx: number; cy: number } {
  const drawW = canvasWidth.value - padding * 2;
  const drawH = canvasHeight.value - padding * 2;

  const xSpan = xRange[1] - xRange[0] || 1;
  const ySpan = yRange[1] - yRange[0] || 1;

  // Maintain aspect ratio
  const scaleX = drawW / xSpan;
  const scaleY = drawH / ySpan;
  const scale = Math.min(scaleX, scaleY) * viewScale.value;

  const centerX = (xRange[0] + xRange[1]) / 2;
  const centerY = (yRange[0] + yRange[1]) / 2;

  const cx =
    canvasWidth.value / 2 +
    (mx - centerX) * scale +
    viewOffset.value.x;
  const cy =
    canvasHeight.value / 2 -
    (my - centerY) * scale +
    viewOffset.value.y;

  return { cx, cy };
}

function computeViewRanges(
  _padding: number
): { xRange: [number, number]; yRange: [number, number] } {
  let yMin = Infinity;
  let yMax = -Infinity;
  let xMinVal = props.xMin;
  let xMaxVal = props.xMax;

  // Sample curves to find y extent
  for (const curve of props.curves) {
    try {
      const pts = sampleCurve(curve, props.xMin, props.xMax, 200);
      for (const p of pts) {
        if (isFinite(p.y) && Math.abs(p.y) < 1000) {
          if (p.y < yMin) yMin = p.y;
          if (p.y > yMax) yMax = p.y;
        }
        if (isFinite(p.x)) {
          if (p.x < xMinVal) xMinVal = p.x;
          if (p.x > xMaxVal) xMaxVal = p.x;
        }
      }
    } catch {
      // skip invalid curves
    }
  }

  // If region is available, use its bounds too
  if (props.region) {
    for (const p of props.region.upperProfile) {
      if (p.y > yMax) yMax = p.y;
      if (p.y < yMin) yMin = p.y;
    }
    for (const p of props.region.lowerProfile) {
      if (p.y > yMax) yMax = p.y;
      if (p.y < yMin) yMin = p.y;
    }
  }

  if (!isFinite(yMin)) yMin = -5;
  if (!isFinite(yMax)) yMax = 5;
  if (yMin === yMax) {
    yMin -= 2;
    yMax += 2;
  }

  // Add margin
  const xMargin = (xMaxVal - xMinVal) * 0.15 || 1;
  const yMargin = (yMax - yMin) * 0.15 || 1;

  return {
    xRange: [xMinVal - xMargin, xMaxVal + xMargin],
    yRange: [yMin - yMargin, yMax + yMargin],
  };
}

function draw() {
  const canvas = canvasRef.value;
  if (!canvas) return;

  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  const dpr = window.devicePixelRatio || 1;
  canvas.width = canvasWidth.value * dpr;
  canvas.height = canvasHeight.value * dpr;
  ctx.scale(dpr, dpr);

  // Clear
  const isDark = document.documentElement.getAttribute("data-theme") === "dark";
  ctx.fillStyle = isDark ? "#1e2030" : "#ffffff";
  ctx.fillRect(0, 0, canvasWidth.value, canvasHeight.value);

  const padding = 40;
  const { xRange, yRange } = computeViewRanges(padding);

  // Draw grid
  drawGrid(ctx, padding, xRange, yRange, isDark);

  // Draw axes
  drawAxes(ctx, padding, xRange, yRange, isDark);

  // Draw filled region
  if (props.region) {
    drawRegion(ctx, padding, xRange, yRange, isDark);
  }

  // Draw curves
  drawCurves(ctx, padding, xRange, yRange);

  // Draw axis of revolution indicator
  drawRevolutionAxis(ctx, padding, xRange, yRange);

  // Draw axis labels and tick values
  drawLabels(ctx, padding, xRange, yRange, isDark);
}

function drawGrid(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number],
  isDark: boolean
) {
  const gridColor = isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.06)";
  const subGridColor = isDark ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.03)";

  ctx.lineWidth = 1;

  // Determine nice grid spacing
  const xSpan = xRange[1] - xRange[0];
  const ySpan = yRange[1] - yRange[0];
  const xStep = niceStep(xSpan / 8);
  const yStep = niceStep(ySpan / 8);

  // Vertical grid lines
  const xStart = Math.ceil(xRange[0] / xStep) * xStep;
  for (let x = xStart; x <= xRange[1]; x += xStep) {
    const { cx } = mathToCanvas(x, 0, padding, xRange, yRange);
    if (cx < 0 || cx > canvasWidth.value) continue;

    ctx.strokeStyle = gridColor;
    ctx.beginPath();
    ctx.moveTo(cx, 0);
    ctx.lineTo(cx, canvasHeight.value);
    ctx.stroke();

    // Sub-grid
    const subStep = xStep / 5;
    for (let sx = x + subStep; sx < x + xStep && sx <= xRange[1]; sx += subStep) {
      const { cx: scx } = mathToCanvas(sx, 0, padding, xRange, yRange);
      if (scx < 0 || scx > canvasWidth.value) continue;
      ctx.strokeStyle = subGridColor;
      ctx.beginPath();
      ctx.moveTo(scx, 0);
      ctx.lineTo(scx, canvasHeight.value);
      ctx.stroke();
    }
  }

  // Horizontal grid lines
  const yStart = Math.ceil(yRange[0] / yStep) * yStep;
  for (let y = yStart; y <= yRange[1]; y += yStep) {
    const { cy } = mathToCanvas(0, y, padding, xRange, yRange);
    if (cy < 0 || cy > canvasHeight.value) continue;

    ctx.strokeStyle = gridColor;
    ctx.beginPath();
    ctx.moveTo(0, cy);
    ctx.lineTo(canvasWidth.value, cy);
    ctx.stroke();

    const subStep = yStep / 5;
    for (let sy = y + subStep; sy < y + yStep && sy <= yRange[1]; sy += subStep) {
      const { cy: scy } = mathToCanvas(0, sy, padding, xRange, yRange);
      if (scy < 0 || scy > canvasHeight.value) continue;
      ctx.strokeStyle = subGridColor;
      ctx.beginPath();
      ctx.moveTo(0, scy);
      ctx.lineTo(canvasWidth.value, scy);
      ctx.stroke();
    }
  }
}

function drawAxes(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number],
  isDark: boolean
) {
  const axisColor = isDark ? "rgba(255,255,255,0.35)" : "rgba(0,0,0,0.35)";
  ctx.strokeStyle = axisColor;
  ctx.lineWidth = 1.5;

  // X axis (y=0)
  const { cy: yZero } = mathToCanvas(0, 0, padding, xRange, yRange);
  if (yZero >= 0 && yZero <= canvasHeight.value) {
    ctx.beginPath();
    ctx.moveTo(0, yZero);
    ctx.lineTo(canvasWidth.value, yZero);
    ctx.stroke();

    // Arrow
    ctx.fillStyle = axisColor;
    ctx.beginPath();
    ctx.moveTo(canvasWidth.value - 2, yZero);
    ctx.lineTo(canvasWidth.value - 10, yZero - 4);
    ctx.lineTo(canvasWidth.value - 10, yZero + 4);
    ctx.fill();
  }

  // Y axis (x=0)
  const { cx: xZero } = mathToCanvas(0, 0, padding, xRange, yRange);
  if (xZero >= 0 && xZero <= canvasWidth.value) {
    ctx.beginPath();
    ctx.moveTo(xZero, 0);
    ctx.lineTo(xZero, canvasHeight.value);
    ctx.stroke();

    // Arrow
    ctx.fillStyle = axisColor;
    ctx.beginPath();
    ctx.moveTo(xZero, 2);
    ctx.lineTo(xZero - 4, 10);
    ctx.lineTo(xZero + 4, 10);
    ctx.fill();
  }
}

function drawLabels(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number],
  isDark: boolean
) {
  const textColor = isDark ? "rgba(255,255,255,0.5)" : "rgba(0,0,0,0.5)";
  ctx.fillStyle = textColor;
  ctx.font = '11px -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.textAlign = "center";
  ctx.textBaseline = "top";

  const xSpan = xRange[1] - xRange[0];
  const ySpan = yRange[1] - yRange[0];
  const xStep = niceStep(xSpan / 8);
  const yStep = niceStep(ySpan / 8);

  const { cy: yZero } = mathToCanvas(0, 0, padding, xRange, yRange);
  const { cx: xZero } = mathToCanvas(0, 0, padding, xRange, yRange);

  // X axis tick labels
  const xStart = Math.ceil(xRange[0] / xStep) * xStep;
  for (let x = xStart; x <= xRange[1]; x += xStep) {
    if (Math.abs(x) < xStep * 0.01) continue; // skip 0
    const { cx } = mathToCanvas(x, 0, padding, xRange, yRange);
    if (cx < 20 || cx > canvasWidth.value - 20) continue;

    const labelY = Math.min(Math.max(yZero + 6, 4), canvasHeight.value - 16);
    ctx.fillText(formatTickLabel(x), cx, labelY);

    // Tick mark
    ctx.strokeStyle = textColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    const tickY = Math.min(Math.max(yZero, 0), canvasHeight.value);
    ctx.moveTo(cx, tickY - 3);
    ctx.lineTo(cx, tickY + 3);
    ctx.stroke();
  }

  // Y axis tick labels
  ctx.textAlign = "right";
  ctx.textBaseline = "middle";
  const yLabelStart = Math.ceil(yRange[0] / yStep) * yStep;
  for (let y = yLabelStart; y <= yRange[1]; y += yStep) {
    if (Math.abs(y) < yStep * 0.01) continue;
    const { cy } = mathToCanvas(0, y, padding, xRange, yRange);
    if (cy < 10 || cy > canvasHeight.value - 10) continue;

    const labelX = Math.min(Math.max(xZero - 6, 30), canvasWidth.value - 4);
    ctx.fillText(formatTickLabel(y), labelX, cy);

    ctx.strokeStyle = textColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    const tickX = Math.min(Math.max(xZero, 0), canvasWidth.value);
    ctx.moveTo(tickX - 3, cy);
    ctx.lineTo(tickX + 3, cy);
    ctx.stroke();
  }

  // Origin label
  if (
    xZero > 10 &&
    xZero < canvasWidth.value - 10 &&
    yZero > 10 &&
    yZero < canvasHeight.value - 10
  ) {
    ctx.textAlign = "right";
    ctx.textBaseline = "top";
    ctx.fillText("O", xZero - 6, yZero + 6);
  }
}

function drawRegion(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number],
  isDark: boolean
) {
  const region = props.region!;
  if (region.upperProfile.length < 2 || region.lowerProfile.length < 2) return;

  ctx.save();

  // Fill the region between upper and lower profiles
  const fillColor = isDark ? "rgba(79, 110, 247, 0.15)" : "rgba(79, 110, 247, 0.12)";
  ctx.fillStyle = fillColor;

  ctx.beginPath();

  // Trace upper profile left to right
  const firstUpperPt = region.upperProfile[0]!;
  const firstUpper = mathToCanvas(
    firstUpperPt.x,
    firstUpperPt.y,
    padding,
    xRange,
    yRange
  );
  ctx.moveTo(firstUpper.cx, firstUpper.cy);

  for (let i = 1; i < region.upperProfile.length; i++) {
    const pt = region.upperProfile[i]!;
    const p = mathToCanvas(
      pt.x,
      pt.y,
      padding,
      xRange,
      yRange
    );
    ctx.lineTo(p.cx, p.cy);
  }

  // Trace lower profile right to left
  for (let i = region.lowerProfile.length - 1; i >= 0; i--) {
    const pt = region.lowerProfile[i]!;
    const p = mathToCanvas(
      pt.x,
      pt.y,
      padding,
      xRange,
      yRange
    );
    ctx.lineTo(p.cx, p.cy);
  }

  ctx.closePath();
  ctx.fill();

  // Stroke the boundary with a subtle line
  ctx.strokeStyle = isDark ? "rgba(79, 110, 247, 0.3)" : "rgba(79, 110, 247, 0.25)";
  ctx.lineWidth = 1;
  ctx.stroke();

  // Draw diagonal hatching inside the region for visual emphasis
  drawHatching(ctx, padding, xRange, yRange, region, isDark);

  ctx.restore();
}

function drawHatching(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number],
  region: ComputedRegion,
  isDark: boolean
) {
  ctx.save();

  // Create clipping path from the region
  ctx.beginPath();
  const hatchFirstUpper = region.upperProfile[0]!;
  const firstUpperH = mathToCanvas(
    hatchFirstUpper.x,
    hatchFirstUpper.y,
    padding,
    xRange,
    yRange
  );
  ctx.moveTo(firstUpperH.cx, firstUpperH.cy);

  for (let i = 1; i < region.upperProfile.length; i++) {
    const pt = region.upperProfile[i]!;
    const p = mathToCanvas(
      pt.x,
      pt.y,
      padding,
      xRange,
      yRange
    );
    ctx.lineTo(p.cx, p.cy);
  }
  for (let i = region.lowerProfile.length - 1; i >= 0; i--) {
    const pt = region.lowerProfile[i]!;
    const p = mathToCanvas(
      pt.x,
      pt.y,
      padding,
      xRange,
      yRange
    );
    ctx.lineTo(p.cx, p.cy);
  }
  ctx.closePath();
  ctx.clip();

  // Draw hatching lines
  ctx.strokeStyle = isDark ? "rgba(79, 110, 247, 0.12)" : "rgba(79, 110, 247, 0.1)";
  ctx.lineWidth = 1;
  const spacing = 8;
  const totalDiag = canvasWidth.value + canvasHeight.value;

  for (let d = -canvasHeight.value; d < totalDiag; d += spacing) {
    ctx.beginPath();
    ctx.moveTo(d, 0);
    ctx.lineTo(d + canvasHeight.value, canvasHeight.value);
    ctx.stroke();
  }

  ctx.restore();
}

function drawCurves(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number]
) {
  for (let ci = 0; ci < props.curves.length; ci++) {
    const curve = props.curves[ci]!;
    const color = curve.color ?? defaultCurveColors[ci % defaultCurveColors.length]!;

    try {
      const xSampleMin = xRange[0];
      const xSampleMax = xRange[1];
      const pts = sampleCurve(curve, xSampleMin, xSampleMax, 500);

      if (pts.length < 2) continue;

      ctx.save();
      ctx.strokeStyle = color!;
      ctx.lineWidth = 2.5;
      ctx.lineJoin = "round";
      ctx.lineCap = "round";

      // Handle vertical lines
      if (curve.type === "x_const") {
        const xVal = parseFloat(curve.expression);
        if (!isFinite(xVal)) continue;

        ctx.setLineDash([6, 4]);
        ctx.lineWidth = 2;
        const { cx } = mathToCanvas(xVal, 0, padding, xRange, yRange);
        ctx.beginPath();
        ctx.moveTo(cx, 0);
        ctx.lineTo(cx, canvasHeight.value);
        ctx.stroke();
        ctx.setLineDash([]);

        // Label
        ctx.fillStyle = color!;
        ctx.font = 'bold 12px -apple-system, "Segoe UI", Roboto, sans-serif';
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(curve!.equation || `x = ${curve!.expression}`, cx + 6, 12);
      } else if (curve.type === "y_const") {
        const yVal = parseFloat(curve!.expression);
        if (!isFinite(yVal)) continue;

        ctx.setLineDash([6, 4]);
        ctx.lineWidth = 2;
        const { cy } = mathToCanvas(0, yVal, padding, xRange, yRange);
        ctx.beginPath();
        ctx.moveTo(0, cy);
        ctx.lineTo(canvasWidth.value, cy);
        ctx.stroke();
        ctx.setLineDash([]);

        // Label
        ctx.fillStyle = color!;
        ctx.font = 'bold 12px -apple-system, "Segoe UI", Roboto, sans-serif';
        ctx.textAlign = "left";
        ctx.textBaseline = "bottom";
        ctx.fillText(curve!.equation || `y = ${curve!.expression}`, 12, cy - 6);
      } else {
        // Regular curve — draw connected segments
        ctx.beginPath();
        let started = false;
        let prevPt: { cx: number; cy: number } | null = null;

        for (const p of pts) {
          if (!isFinite(p.y) || Math.abs(p.y) > 1e6) {
            started = false;
            prevPt = null;
            continue;
          }

          const cp = mathToCanvas(p.x, p.y, padding, xRange, yRange);

          // Detect large jumps (discontinuities)
          if (prevPt && Math.abs(cp.cy - prevPt.cy) > canvasHeight.value * 0.8) {
            ctx.stroke();
            ctx.beginPath();
            started = false;
          }

          if (!started) {
            ctx.moveTo(cp.cx, cp.cy);
            started = true;
          } else {
            ctx.lineTo(cp.cx, cp.cy);
          }
          prevPt = cp;
        }
        ctx.stroke();

        // Curve label near the right side
        const labelIdx = Math.min(Math.floor(pts.length * 0.75), pts.length - 1);
        const labelPt = pts[labelIdx];
        if (labelPt && isFinite(labelPt.y)) {
          const lp = mathToCanvas(labelPt.x, labelPt.y, padding, xRange, yRange);
          if (
            lp.cx > 20 &&
            lp.cx < canvasWidth.value - 20 &&
            lp.cy > 20 &&
            lp.cy < canvasHeight.value - 20
          ) {
            ctx.fillStyle = color!;
            ctx.font = 'bold 12px -apple-system, "Segoe UI", Roboto, sans-serif';
            ctx.textAlign = "left";
            ctx.textBaseline = "bottom";

            const label = curve!.equation
              || ((curve!.type === "y_of_x" ? "y = " : curve!.type === "x_of_y" ? "x = " : "") + curve!.expression);
            ctx.fillText(label, lp.cx + 6, lp.cy - 6);
          }
        }
      }

      ctx.restore();
    } catch {
      // Skip invalid curves
    }
  }
}

function drawRevolutionAxis(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number]
) {
  ctx.save();

  ctx.strokeStyle = "#ff6b6b";
  ctx.lineWidth = 2;
  ctx.setLineDash([8, 5]);
  ctx.globalAlpha = 0.7;

  if (props.axis === "x") {
    // Horizontal axis at y = axisValue
    const { cy } = mathToCanvas(0, props.axisValue, padding, xRange, yRange);
    ctx.beginPath();
    ctx.moveTo(0, cy);
    ctx.lineTo(canvasWidth.value, cy);
    ctx.stroke();

    // Label
    ctx.setLineDash([]);
    ctx.globalAlpha = 1;
    ctx.fillStyle = "#ff6b6b";
    ctx.font = 'bold 11px -apple-system, "Segoe UI", Roboto, sans-serif';
    ctx.textAlign = "right";
    ctx.textBaseline = "bottom";
    const label =
      props.axisValue === 0
        ? "rotation axis (x-axis)"
        : `rotation axis (y = ${props.axisValue})`;
    ctx.fillText(label, canvasWidth.value - 8, cy - 4);
  } else {
    // Vertical axis at x = axisValue
    const { cx } = mathToCanvas(props.axisValue, 0, padding, xRange, yRange);
    ctx.beginPath();
    ctx.moveTo(cx, 0);
    ctx.lineTo(cx, canvasHeight.value);
    ctx.stroke();

    // Label
    ctx.setLineDash([]);
    ctx.globalAlpha = 1;
    ctx.fillStyle = "#ff6b6b";
    ctx.font = 'bold 11px -apple-system, "Segoe UI", Roboto, sans-serif';
    ctx.textAlign = "left";
    ctx.textBaseline = "top";
    const label =
      props.axisValue === 0
        ? "rotation axis (y-axis)"
        : `rotation axis (x = ${props.axisValue})`;
    ctx.fillText(label, cx + 6, 12);
  }

  // Draw a small rotation arrow icon near the axis
  drawRotationIcon(ctx, padding, xRange, yRange);

  ctx.restore();
}

function drawRotationIcon(
  ctx: CanvasRenderingContext2D,
  padding: number,
  xRange: [number, number],
  yRange: [number, number]
) {
  let cx: number, cy: number;

  if (props.axis === "x") {
    const mid = (props.xMin + props.xMax) / 2;
    const converted = mathToCanvas(mid, props.axisValue, padding, xRange, yRange);
    cx = converted.cx;
    cy = converted.cy;
  } else {
    const midY = 0;
    const converted = mathToCanvas(props.axisValue, midY, padding, xRange, yRange);
    cx = converted.cx;
    cy = converted.cy;
  }

  // Draw a circular arc arrow
  ctx.save();
  ctx.strokeStyle = "#ff6b6b";
  ctx.fillStyle = "#ff6b6b";
  ctx.lineWidth = 1.5;
  ctx.setLineDash([]);
  ctx.globalAlpha = 0.6;

  const r = 12;
  ctx.beginPath();
  ctx.arc(cx, cy, r, -Math.PI * 0.8, Math.PI * 0.5, false);
  ctx.stroke();

  // Arrowhead
  const arrowAngle = Math.PI * 0.5;
  const ax = cx + r * Math.cos(arrowAngle);
  const ay = cy + r * Math.sin(arrowAngle);
  ctx.beginPath();
  ctx.moveTo(ax, ay);
  ctx.lineTo(ax + 5, ay - 3);
  ctx.lineTo(ax + 2, ay + 4);
  ctx.fill();

  ctx.restore();
}

// ===== Helper functions =====

function niceStep(rawStep: number): number {
  if (rawStep <= 0) return 1;
  const magnitude = Math.pow(10, Math.floor(Math.log10(rawStep)));
  const residual = rawStep / magnitude;

  if (residual <= 1.5) return magnitude;
  if (residual <= 3.5) return 2 * magnitude;
  if (residual <= 7.5) return 5 * magnitude;
  return 10 * magnitude;
}

function formatTickLabel(value: number): string {
  if (Math.abs(value) < 1e-10) return "0";
  if (Math.abs(value) >= 1000 || (Math.abs(value) < 0.01 && Math.abs(value) > 0)) {
    return value.toExponential(1);
  }
  // Remove trailing zeros
  const s = value.toPrecision(4);
  return parseFloat(s).toString();
}

// ===== Mouse/touch interaction =====

function onMouseDown(e: MouseEvent) {
  if (e.button !== 0) return;
  isDragging.value = true;
  lastMousePos.value = { x: e.clientX, y: e.clientY };
}

function onMouseMove(e: MouseEvent) {
  if (!isDragging.value) return;

  const dx = e.clientX - lastMousePos.value.x;
  const dy = e.clientY - lastMousePos.value.y;
  lastMousePos.value = { x: e.clientX, y: e.clientY };

  viewOffset.value = {
    x: viewOffset.value.x + dx,
    y: viewOffset.value.y + dy,
  };
  draw();
}

function onMouseUp() {
  isDragging.value = false;
}

function onWheel(_e: WheelEvent) {
  // keep wheel behavior disabled so parent/page scroll remains available
}

function onTouchStart(e: TouchEvent) {
  if (e.touches.length === 1) {
    const t = e.touches[0]!;
    lastTouchCenter = { x: t.clientX, y: t.clientY };
  } else if (e.touches.length >= 2) {
    const t1 = e.touches[0]!;
    const t2 = e.touches[1]!;
    const dx = t2.clientX - t1.clientX;
    const dy = t2.clientY - t1.clientY;
    pinchStartDistance = Math.hypot(dx, dy);
    pinchStartScale = viewScale.value;
    lastTouchCenter = {
      x: (t1.clientX + t2.clientX) / 2,
      y: (t1.clientY + t2.clientY) / 2,
    };
  }
}

function onTouchMove(e: TouchEvent) {
  if (e.touches.length === 1 && lastTouchCenter) {
    const t = e.touches[0]!;
    const dx = t.clientX - lastTouchCenter.x;
    const dy = t.clientY - lastTouchCenter.y;
    lastTouchCenter = { x: t.clientX, y: t.clientY };

    viewOffset.value = {
      x: viewOffset.value.x + dx,
      y: viewOffset.value.y + dy,
    };
    draw();
    return;
  }

  if (e.touches.length >= 2) {
    const t1 = e.touches[0]!;
    const t2 = e.touches[1]!;
    const dx = t2.clientX - t1.clientX;
    const dy = t2.clientY - t1.clientY;
    const dist = Math.hypot(dx, dy);

    if (pinchStartDistance > 0) {
      const rawScale = pinchStartScale * (dist / pinchStartDistance);
      viewScale.value = Math.min(8, Math.max(0.2, rawScale));
      draw();
    }

    lastTouchCenter = {
      x: (t1.clientX + t2.clientX) / 2,
      y: (t1.clientY + t2.clientY) / 2,
    };
  }
}

function onTouchEnd(e: TouchEvent) {
  if (e.touches.length === 0) {
    lastTouchCenter = null;
    pinchStartDistance = 0;
  } else if (e.touches.length === 1) {
    const t = e.touches[0]!;
    lastTouchCenter = { x: t.clientX, y: t.clientY };
    pinchStartDistance = 0;
    pinchStartScale = viewScale.value;
  }
}

function resetView() {
  viewOffset.value = { x: 0, y: 0 };
  viewScale.value = 1;
  draw();
}

// ===== Lifecycle & Watchers =====

function updateCanvasSize() {
  const container = containerRef.value;
  if (!container) return;
  canvasWidth.value = container.clientWidth;
  canvasHeight.value = Math.max(container.clientHeight, 300);
  draw();
}

let resizeObserver: ResizeObserver | null = null;

onMounted(() => {
  updateCanvasSize();
  draw();

  if (containerRef.value) {
    resizeObserver = new ResizeObserver(() => {
      updateCanvasSize();
    });
    resizeObserver.observe(containerRef.value);
  }

  document.addEventListener("mousemove", onMouseMove);
  document.addEventListener("mouseup", onMouseUp);
});

onUnmounted(() => {
  if (resizeObserver) {
    resizeObserver.disconnect();
  }
  document.removeEventListener("mousemove", onMouseMove);
  document.removeEventListener("mouseup", onMouseUp);
});

watch(
  () => [props.curves, props.region, props.xMin, props.xMax, props.axis, props.axisValue],
  () => {
    // Reset view when input changes
    viewOffset.value = { x: 0, y: 0 };
    viewScale.value = 1;
    draw();
  },
  { deep: true }
);

// Watch theme changes
const themeObserver = ref<MutationObserver | null>(null);
onMounted(() => {
  themeObserver.value = new MutationObserver(() => {
    draw();
  });
  themeObserver.value.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["data-theme"],
  });
});
onUnmounted(() => {
  themeObserver.value?.disconnect();
});

defineExpose({ resetView, draw });
</script>

<template>
  <div ref="containerRef" class="canvas2d-container">
    <canvas
      ref="canvasRef"
      class="canvas2d"
      :style="{ width: canvasWidth + 'px', height: canvasHeight + 'px' }"
      @mousedown="onMouseDown"
      @wheel.passive="onWheel"
      @touchstart.passive="onTouchStart"
      @touchmove.passive="onTouchMove"
      @touchend.passive="onTouchEnd"
    />
    <div class="canvas2d-controls">
      <button class="btn btn-sm btn-icon" title="Reset view" @click="resetView">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
             stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
          <path d="M3 3v5h5" />
        </svg>
      </button>
      <button class="btn btn-sm btn-icon" title="Zoom in" @click="viewScale *= 1.2; draw()">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
             stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
          <line x1="11" y1="8" x2="11" y2="14" />
          <line x1="8" y1="11" x2="14" y2="11" />
        </svg>
      </button>
      <button class="btn btn-sm btn-icon" title="Zoom out" @click="viewScale *= 0.8; draw()">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
             stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
          <line x1="8" y1="11" x2="14" y2="11" />
        </svg>
      </button>
    </div>

  </div>
</template>

<style scoped>
.canvas2d-container {
  position: relative;
  width: 100%;
  height: 100%;
  min-height: 300px;
  overflow: hidden;
  border-radius: var(--radius-md);
  background: var(--c-bg-card);
}

.canvas2d {
  display: block;
  cursor: grab;
  touch-action: pan-x pan-y pinch-zoom;
}

.canvas2d:active {
  cursor: grabbing;
}

.canvas2d-controls {
  position: absolute;
  top: 10px;
  right: 10px;
  display: flex;
  flex-direction: column;
  gap: 4px;
  z-index: 5;
}

.canvas2d-controls .btn-icon {
  width: 30px;
  height: 30px;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--c-bg-soft);
  border: 1px solid var(--c-border);
  border-radius: var(--radius-sm);
  opacity: 0.75;
  transition: opacity 0.15s ease;
}

.canvas2d-controls .btn-icon:hover {
  opacity: 1;
}

.canvas2d-hint {
  position: absolute;
  bottom: 8px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: 0.72rem;
  background: var(--c-bg-soft);
  border: 1px solid var(--c-border-light);
  padding: 3px 10px;
  border-radius: 999px;
  opacity: 0.6;
  pointer-events: none;
  white-space: nowrap;
}
</style>

// src/components/revolution/Canvas2D.tsx
import React, {
  useRef,
  useEffect,
  useState,
  useCallback,
  forwardRef,
  useImperativeHandle,
} from "react";
import { ZoomIn, ZoomOut } from "lucide-react";
import type { ComputedRegion, CurveDefinition } from "@/utils/types";
import { sampleCurve } from "@/utils/mathEngine";

export interface Canvas2DProps {
  curves: CurveDefinition[];
  region: ComputedRegion | null;
  axis: "x" | "y";
  axisValue: number;
  xMin: number;
  xMax: number;
}

export interface Canvas2DHandle {
  takeScreenshot: () => string | null;
}

/** Format a number for display: strip trailing zeros, limit decimals */
function formatTickValue(v: number): string {
  if (Math.abs(v) < 1e-10) return "0";
  if (Math.abs(v) >= 1000 || (Math.abs(v) < 0.01 && v !== 0)) {
    return v.toExponential(1);
  }
  // Round to 2 decimal places max
  const s = v.toFixed(2);
  // Strip trailing zeros
  return s.replace(/\.?0+$/, "");
}

/**
 * Find intersection points between pairs of curves in the given x range.
 * Returns array of {x, y} points.
 */
function findIntersections(
  curves: CurveDefinition[],
  viewMinX: number,
  viewMaxX: number,
): { x: number; y: number }[] {
  const intersections: { x: number; y: number }[] = [];
  const steps = 500;
  const dx = (viewMaxX - viewMinX) / steps;

  for (let ci = 0; ci < curves.length; ci++) {
    for (let cj = ci + 1; cj < curves.length; cj++) {
      const pts1 = sampleCurve(curves[ci]!, viewMinX, viewMaxX, steps);
      const pts2 = sampleCurve(curves[cj]!, viewMinX, viewMaxX, steps);

      if (pts1.length < 2 || pts2.length < 2) continue;

      // Build lookup maps indexed by x for fast comparison
      const map2 = new Map<number, number>();
      for (const p of pts2) {
        // Round x to avoid floating point mismatch
        map2.set(Math.round(p.x * 1e8) / 1e8, p.y);
      }

      let prevDiff: number | null = null;
      let prevX = viewMinX;

      for (const p1 of pts1) {
        const key = Math.round(p1.x * 1e8) / 1e8;
        const y2 = map2.get(key);
        if (y2 === undefined || !isFinite(p1.y) || !isFinite(y2)) {
          prevDiff = null;
          continue;
        }

        const diff = p1.y - y2;

        if (
          prevDiff !== null &&
          prevDiff * diff <= 0 &&
          Math.abs(diff - prevDiff) < 100
        ) {
          // Sign change — bisect to find intersection
          let lo = prevX;
          let hi = p1.x;
          for (let iter = 0; iter < 20; iter++) {
            const mid = (lo + hi) / 2;
            const s1 = sampleCurve(
              curves[ci]!,
              mid - dx * 0.001,
              mid + dx * 0.001,
              1,
            );
            const s2 = sampleCurve(
              curves[cj]!,
              mid - dx * 0.001,
              mid + dx * 0.001,
              1,
            );
            if (s1.length === 0 || s2.length === 0) break;
            const midDiff = s1[0]!.y - s2[0]!.y;
            if (!isFinite(midDiff)) break;
            if (prevDiff * midDiff <= 0) {
              hi = mid;
            } else {
              lo = mid;
            }
          }
          const ix = (lo + hi) / 2;
          const sp = sampleCurve(
            curves[ci]!,
            ix - dx * 0.001,
            ix + dx * 0.001,
            1,
          );
          if (sp.length > 0 && isFinite(sp[0]!.y)) {
            // Deduplicate: check if we already have a nearby intersection
            const iy = sp[0]!.y;
            const isDup = intersections.some(
              (pt) =>
                Math.abs(pt.x - ix) < dx * 2 && Math.abs(pt.y - iy) < 0.01,
            );
            if (!isDup) {
              intersections.push({ x: ix, y: iy });
            }
          }
        }

        prevDiff = diff;
        prevX = p1.x;
      }
    }
  }

  return intersections;
}

const Canvas2D = forwardRef<Canvas2DHandle, Canvas2DProps>(function Canvas2D(
  { curves, region, axis, axisValue, xMin, xMax },
  ref,
) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Viewport state
  const [view, setView] = useState({
    centerX: 0,
    centerY: 0,
    scale: 50, // pixels per unit
  });

  // Expose screenshot method to parent
  useImperativeHandle(ref, () => ({
    takeScreenshot: () => {
      const canvas = canvasRef.current;
      if (!canvas) return null;
      return canvas.toDataURL("image/png");
    },
  }));

  // Interaction state
  const isDragging = useRef(false);
  const lastMouse = useRef({ x: 0, y: 0 });

  // Auto-fit when region or bounds change
  useEffect(() => {
    if (!containerRef.current) return;
    const { width, height } = containerRef.current.getBoundingClientRect();

    let minX = xMin;
    let maxX = xMax;
    let minY = -5;
    let maxY = 5;

    if (region) {
      minX = region.xMin;
      maxX = region.xMax;

      let rMinY = Infinity;
      let rMaxY = -Infinity;

      for (const p of region.upperProfile) {
        if (p.y > rMaxY) rMaxY = p.y;
        if (p.y < rMinY) rMinY = p.y;
      }
      for (const p of region.lowerProfile) {
        if (p.y > rMaxY) rMaxY = p.y;
        if (p.y < rMinY) rMinY = p.y;
      }

      if (rMinY !== Infinity && rMaxY !== -Infinity) {
        minY = rMinY;
        maxY = rMaxY;
      }
    }

    const padding = 1.5;
    const dx = maxX - minX || 10;
    const dy = maxY - minY || 10;

    const scaleX = width / (dx * padding);
    const scaleY = height / (dy * padding);
    const scale = Math.min(scaleX, scaleY, 200);

    setView({
      centerX: (minX + maxX) / 2,
      centerY: (minY + maxY) / 2,
      scale: Math.max(scale, 10),
    });
  }, [region, xMin, xMax]);

  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    const container = containerRef.current;
    if (!canvas || !container) return;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const { width, height } = container.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;

    canvas.width = width * dpr;
    canvas.height = height * dpr;
    canvas.style.width = `${width}px`;
    canvas.style.height = `${height}px`;

    ctx.scale(dpr, dpr);
    ctx.clearRect(0, 0, width, height);

    const { centerX, centerY, scale } = view;

    // Coordinate transforms
    const toScreenX = (x: number) => width / 2 + (x - centerX) * scale;
    const toScreenY = (y: number) => height / 2 - (y - centerY) * scale;

    // Determine grid step
    const step = scale > 100 ? 0.5 : scale > 40 ? 1 : scale > 10 ? 5 : 10;

    const startX = Math.floor((centerX - width / 2 / scale) / step) * step;
    const endX = Math.ceil((centerX + width / 2 / scale) / step) * step;
    const startY = Math.floor((centerY - height / 2 / scale) / step) * step;
    const endY = Math.ceil((centerY + height / 2 / scale) / step) * step;

    // ===== Draw Grid =====
    ctx.strokeStyle = "rgba(150, 150, 150, 0.15)";
    ctx.lineWidth = 1;

    ctx.beginPath();
    for (let x = startX; x <= endX; x += step) {
      const sx = toScreenX(x);
      ctx.moveTo(sx, 0);
      ctx.lineTo(sx, height);
    }
    for (let y = startY; y <= endY; y += step) {
      const sy = toScreenY(y);
      ctx.moveTo(0, sy);
      ctx.lineTo(width, sy);
    }
    ctx.stroke();

    // ===== Draw Axes =====
    ctx.strokeStyle = "rgba(150, 150, 150, 0.5)";
    ctx.lineWidth = 2;
    ctx.beginPath();
    const originX = toScreenX(0);
    const originY = toScreenY(0);

    if (originX >= 0 && originX <= width) {
      ctx.moveTo(originX, 0);
      ctx.lineTo(originX, height);
    }
    if (originY >= 0 && originY <= height) {
      ctx.moveTo(0, originY);
      ctx.lineTo(width, originY);
    }
    ctx.stroke();

    // ===== Draw Axis Labels (arrows and label text) =====
    const isDark =
      document.documentElement.getAttribute("data-theme") === "dark";
    const labelColor = isDark
      ? "rgba(200, 205, 220, 0.8)"
      : "rgba(80, 85, 100, 0.8)";
    const tickTextColor = isDark
      ? "rgba(160, 165, 180, 0.7)"
      : "rgba(90, 95, 110, 0.65)";

    // Axis arrows
    ctx.fillStyle = labelColor;
    ctx.font = "bold 13px sans-serif";
    ctx.textAlign = "left";
    ctx.textBaseline = "middle";

    // X-axis label
    if (originY >= 0 && originY <= height) {
      ctx.fillText("x", width - 16, originY - 12);
    }
    // Y-axis label
    if (originX >= 0 && originX <= width) {
      ctx.textAlign = "center";
      ctx.fillText("y", originX + 14, 14);
    }

    // ===== Draw Axis Tick Values =====
    ctx.font = "11px sans-serif";
    ctx.fillStyle = tickTextColor;

    // X-axis ticks
    if (originY >= -20 && originY <= height + 20) {
      const tickY = Math.min(Math.max(originY, 0), height);
      ctx.textAlign = "center";
      ctx.textBaseline = "top";
      for (let x = startX; x <= endX; x += step) {
        if (Math.abs(x) < step * 0.01) continue; // skip 0
        const sx = toScreenX(x);
        if (sx < 20 || sx > width - 20) continue;

        // Draw tick mark
        ctx.strokeStyle = "rgba(150, 150, 150, 0.4)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(sx, tickY - 3);
        ctx.lineTo(sx, tickY + 3);
        ctx.stroke();

        // Draw value
        ctx.fillStyle = tickTextColor;
        ctx.fillText(formatTickValue(x), sx, tickY + 5);
      }
    }

    // Y-axis ticks
    if (originX >= -20 && originX <= width + 20) {
      const tickX = Math.min(Math.max(originX, 0), width);
      ctx.textAlign = "right";
      ctx.textBaseline = "middle";
      for (let y = startY; y <= endY; y += step) {
        if (Math.abs(y) < step * 0.01) continue; // skip 0
        const sy = toScreenY(y);
        if (sy < 15 || sy > height - 15) continue;

        // Draw tick mark
        ctx.strokeStyle = "rgba(150, 150, 150, 0.4)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(tickX - 3, sy);
        ctx.lineTo(tickX + 3, sy);
        ctx.stroke();

        // Draw value
        ctx.fillStyle = tickTextColor;
        ctx.fillText(formatTickValue(y), tickX - 6, sy);
      }
    }

    // Origin "O" label
    if (
      originX >= 5 &&
      originX <= width - 5 &&
      originY >= 5 &&
      originY <= height - 5
    ) {
      ctx.fillStyle = tickTextColor;
      ctx.font = "11px sans-serif";
      ctx.textAlign = "right";
      ctx.textBaseline = "top";
      ctx.fillText("O", originX - 5, originY + 4);
    }

    // ===== Draw Region =====
    if (region) {
      ctx.fillStyle = "rgba(79, 110, 247, 0.2)";
      ctx.beginPath();

      for (let i = 0; i < region.upperProfile.length; i++) {
        const p = region.upperProfile[i]!;
        const sx = toScreenX(p.x);
        const sy = toScreenY(p.y);
        if (i === 0) ctx.moveTo(sx, sy);
        else ctx.lineTo(sx, sy);
      }

      for (let i = region.lowerProfile.length - 1; i >= 0; i--) {
        const p = region.lowerProfile[i]!;
        const sx = toScreenX(p.x);
        const sy = toScreenY(p.y);
        ctx.lineTo(sx, sy);
      }

      ctx.closePath();
      ctx.fill();

      // Draw region boundaries
      ctx.strokeStyle = "rgba(79, 110, 247, 0.8)";
      ctx.lineWidth = 2;
      ctx.stroke();
    }

    // ===== Draw Curves =====
    const viewMinX = centerX - width / 2 / scale;
    const viewMaxX = centerX + width / 2 / scale;

    for (const curve of curves) {
      const points = sampleCurve(curve, viewMinX, viewMaxX, 500);
      if (points.length === 0) continue;

      ctx.strokeStyle = curve.color || "#4f6ef7";
      ctx.lineWidth = 2;
      ctx.beginPath();

      let isFirst = true;
      for (const p of points) {
        const sx = toScreenX(p.x);
        const sy = toScreenY(p.y);

        if (isNaN(sy) || !isFinite(sy)) {
          isFirst = true;
          continue;
        }

        if (isFirst) {
          ctx.moveTo(sx, sy);
          isFirst = false;
        } else {
          ctx.lineTo(sx, sy);
        }
      }
      ctx.stroke();
    }

    // ===== Draw Revolution Axis =====
    ctx.strokeStyle = "#ef4444";
    ctx.lineWidth = 2;
    ctx.setLineDash([5, 5]);
    ctx.beginPath();

    if (axis === "x") {
      const sy = toScreenY(axisValue);
      ctx.moveTo(0, sy);
      ctx.lineTo(width, sy);
    } else {
      const sx = toScreenX(axisValue);
      ctx.moveTo(sx, 0);
      ctx.lineTo(sx, height);
    }
    ctx.stroke();
    ctx.setLineDash([]);

    // ===== Draw Intersection Points (Bug #8) =====
    if (curves.length >= 2) {
      const intersections = findIntersections(curves, viewMinX, viewMaxX);

      const intersectionColor = isDark ? "#fbbf24" : "#d97706";
      const intersectionBg = isDark
        ? "rgba(251, 191, 36, 0.15)"
        : "rgba(217, 119, 6, 0.1)";

      for (const pt of intersections) {
        const sx = toScreenX(pt.x);
        const sy = toScreenY(pt.y);

        if (sx < -20 || sx > width + 20 || sy < -20 || sy > height + 20)
          continue;

        // Draw point circle
        ctx.beginPath();
        ctx.arc(sx, sy, 5, 0, Math.PI * 2);
        ctx.fillStyle = intersectionColor;
        ctx.fill();
        ctx.strokeStyle = isDark ? "#1e2030" : "#ffffff";
        ctx.lineWidth = 2;
        ctx.stroke();

        // Draw label background and text
        const xStr = formatTickValue(Math.round(pt.x * 1000) / 1000);
        const yStr = formatTickValue(Math.round(pt.y * 1000) / 1000);
        const label = `(${xStr}, ${yStr})`;

        ctx.font = "bold 11px sans-serif";
        const textMetrics = ctx.measureText(label);
        const textW = textMetrics.width + 10;
        const textH = 18;

        // Position label: try top-right of the point, adjust if out of bounds
        let labelX = sx + 10;
        let labelY = sy - 22;
        if (labelX + textW > width - 5) labelX = sx - textW - 5;
        if (labelY < 5) labelY = sy + 10;

        // Background pill
        ctx.fillStyle = intersectionBg;
        ctx.strokeStyle = intersectionColor;
        ctx.lineWidth = 1;
        ctx.beginPath();
        const r = 4;
        ctx.moveTo(labelX + r, labelY);
        ctx.lineTo(labelX + textW - r, labelY);
        ctx.arcTo(labelX + textW, labelY, labelX + textW, labelY + r, r);
        ctx.lineTo(labelX + textW, labelY + textH - r);
        ctx.arcTo(
          labelX + textW,
          labelY + textH,
          labelX + textW - r,
          labelY + textH,
          r,
        );
        ctx.lineTo(labelX + r, labelY + textH);
        ctx.arcTo(labelX, labelY + textH, labelX, labelY + textH - r, r);
        ctx.lineTo(labelX, labelY + r);
        ctx.arcTo(labelX, labelY, labelX + r, labelY, r);
        ctx.closePath();
        ctx.fill();
        ctx.stroke();

        // Label text
        ctx.fillStyle = intersectionColor;
        ctx.textAlign = "left";
        ctx.textBaseline = "middle";
        ctx.fillText(label, labelX + 5, labelY + textH / 2);

        // Draw dashed projection lines to axes
        ctx.strokeStyle = intersectionColor;
        ctx.lineWidth = 1;
        ctx.setLineDash([3, 3]);
        ctx.globalAlpha = 0.4;

        // Projection to X-axis (vertical line from point down to x-axis)
        if (originY >= 0 && originY <= height) {
          ctx.beginPath();
          ctx.moveTo(sx, sy);
          ctx.lineTo(sx, originY);
          ctx.stroke();

          // Small tick mark and value on x-axis
          ctx.globalAlpha = 0.8;
          ctx.setLineDash([]);
          ctx.beginPath();
          ctx.moveTo(sx, originY - 4);
          ctx.lineTo(sx, originY + 4);
          ctx.stroke();

          ctx.fillStyle = intersectionColor;
          ctx.font = "bold 10px sans-serif";
          ctx.textAlign = "center";
          ctx.textBaseline = "top";
          ctx.fillText(xStr, sx, originY + 6);
          ctx.setLineDash([3, 3]);
          ctx.globalAlpha = 0.4;
        }

        // Projection to Y-axis (horizontal line from point to y-axis)
        if (originX >= 0 && originX <= width) {
          ctx.beginPath();
          ctx.moveTo(sx, sy);
          ctx.lineTo(originX, sy);
          ctx.stroke();

          // Small tick mark and value on y-axis
          ctx.globalAlpha = 0.8;
          ctx.setLineDash([]);
          ctx.beginPath();
          ctx.moveTo(originX - 4, sy);
          ctx.lineTo(originX + 4, sy);
          ctx.stroke();

          ctx.fillStyle = intersectionColor;
          ctx.font = "bold 10px sans-serif";
          ctx.textAlign = "right";
          ctx.textBaseline = "middle";
          ctx.fillText(yStr, originX - 6, sy);
          ctx.setLineDash([3, 3]);
          ctx.globalAlpha = 0.4;
        }

        ctx.globalAlpha = 1.0;
        ctx.setLineDash([]);
      }
    }
  }, [curves, region, axis, axisValue, view]);

  useEffect(() => {
    draw();
  }, [draw]);

  useEffect(() => {
    const handleResize = () => draw();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, [draw]);

  // Interaction handlers
  const handleMouseDown = (e: React.MouseEvent) => {
    isDragging.current = true;
    lastMouse.current = { x: e.clientX, y: e.clientY };
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDragging.current) return;

    const dx = e.clientX - lastMouse.current.x;
    const dy = e.clientY - lastMouse.current.y;

    setView((prev) => ({
      ...prev,
      centerX: prev.centerX - dx / prev.scale,
      centerY: prev.centerY + dy / prev.scale,
    }));

    lastMouse.current = { x: e.clientX, y: e.clientY };
  };

  const handleMouseUp = () => {
    isDragging.current = false;
  };

  const handleWheel = (e: React.WheelEvent) => {
    e.preventDefault();
    const zoomFactor = e.deltaY > 0 ? 0.9 : 1.1;

    setView((prev) => ({
      ...prev,
      scale: Math.max(1, Math.min(prev.scale * zoomFactor, 1000)),
    }));
  };

  return (
    <div
      ref={containerRef}
      className="w-full h-full relative overflow-hidden bg-bg cursor-move"
      onMouseDown={handleMouseDown}
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
      onWheel={handleWheel}
      onContextMenu={(e) => e.preventDefault()}
    >
      <canvas
        ref={canvasRef}
        className="absolute inset-0 pointer-events-none"
      />

      {/* Controls overlay */}
      <div className="absolute bottom-4 right-4 flex gap-2">
        <button
          className="w-8 h-8 bg-bg-soft border border-border rounded-md flex items-center justify-center text-text hover:bg-bg transition-colors shadow-sm"
          onClick={() =>
            setView((prev) => ({ ...prev, scale: prev.scale * 1.2 }))
          }
          title="Zoom In"
        >
          <ZoomIn size={16} />
        </button>
        <button
          className="w-8 h-8 bg-bg-soft border border-border rounded-md flex items-center justify-center text-text hover:bg-bg transition-colors shadow-sm"
          onClick={() =>
            setView((prev) => ({ ...prev, scale: prev.scale / 1.2 }))
          }
          title="Zoom Out"
        >
          <ZoomOut size={16} />
        </button>
      </div>
    </div>
  );
});

export default Canvas2D;
