// src/pages/Home.tsx
import { Link } from "react-router-dom";
import {
  Box,
  Grid3X3,
  LineChart,
  TrendingUp,
  Shapes,
  BarChart3,
  ArrowRight,
} from "lucide-react";
import { useTranslation } from "@/i18n";

const tools = [
  {
    id: "revolution",
    path: "/revolution",
    icon: Box,
    titleKey: "home.tools.revolution.title",
    descKey: "home.tools.revolution.desc",
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    disabled: false,
  },
  {
    id: "matrix",
    path: "/matrix",
    icon: Grid3X3,
    titleKey: "home.tools.matrix.title",
    descKey: "home.tools.matrix.desc",
    color: "text-green-500",
    bg: "bg-green-500/10",
    disabled: true,
  },
  {
    id: "graphing",
    path: "/graphing",
    icon: LineChart,
    titleKey: "home.tools.graphing.title",
    descKey: "home.tools.graphing.desc",
    color: "text-purple-500",
    bg: "bg-purple-500/10",
    disabled: true,
  },
  {
    id: "derivatives",
    path: "/derivatives",
    icon: TrendingUp,
    titleKey: "home.tools.derivatives.title",
    descKey: "home.tools.derivatives.desc",
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    disabled: true,
  },
  {
    id: "geometry",
    path: "/geometry",
    icon: Shapes,
    titleKey: "home.tools.geometry.title",
    descKey: "home.tools.geometry.desc",
    color: "text-pink-500",
    bg: "bg-pink-500/10",
    disabled: true,
  },
  {
    id: "statistics",
    path: "/statistics",
    icon: BarChart3,
    titleKey: "home.tools.statistics.title",
    descKey: "home.tools.statistics.desc",
    color: "text-teal-500",
    bg: "bg-teal-500/10",
    disabled: true,
  },
];

export default function Home() {
  const { t } = useTranslation();

  return (
    <div className="h-full overflow-y-auto bg-bg">
      <div className="max-w-6xl mx-auto px-4 py-12 md:py-20">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-6xl font-extrabold mb-6 tracking-tight hero-title-gradient">
            {t("home.hero.title", "Interactive Math Tools")}
          </h1>
          <p className="text-lg md:text-xl text-text-soft max-w-2xl mx-auto leading-relaxed">
            {t(
              "home.hero.subtitle",
              "Visualize, calculate, and explore mathematical concepts with our suite of powerful tools.",
            )}
          </p>
        </div>

        {/* Tools Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {tools.map((tool) => {
            const Icon = tool.icon;
            const isPlaceholder = tool.disabled;

            const CardContent = (
              <div
                className={`card p-6 h-full flex flex-col border border-border bg-bg-soft ${
                  isPlaceholder
                    ? "opacity-60 grayscale cursor-not-allowed"
                    : "hover:-translate-y-1 hover:shadow-card transition-all duration-300 cursor-pointer"
                }`}
              >
                <div className="flex items-center gap-4 mb-4">
                  <div className={`p-3 rounded-xl ${tool.bg} ${tool.color}`}>
                    <Icon size={28} />
                  </div>
                  <h2 className="text-xl font-bold text-text">
                    {t(tool.titleKey, tool.id)}
                  </h2>
                </div>
                <p className="text-text-soft flex-1 leading-relaxed">
                  {t(tool.descKey, `Description for ${tool.id}`)}
                </p>
                <div className="mt-6 flex items-center text-sm font-medium">
                  {isPlaceholder ? (
                    <span className="text-text-soft bg-bg px-3 py-1 rounded-full border border-border">
                      {t("common.comingSoon", "Coming Soon")}
                    </span>
                  ) : (
                    <span className="text-primary flex items-center gap-1 group-hover:gap-2 transition-all">
                      {t("common.tryNow", "Try Now")} <ArrowRight size={16} />
                    </span>
                  )}
                </div>
              </div>
            );

            return isPlaceholder ? (
              <div key={tool.id}>{CardContent}</div>
            ) : (
              <Link to={tool.path} key={tool.id} className="block group">
                {CardContent}
              </Link>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// src/pages/Home.vue
<script setup lang="ts">
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import {
    ArrowRight,
    ChevronRight,
    RefreshCw,
    Calculator,
    LineChart,
    FunctionSquare,
    Ruler,
    BarChart3,
} from "lucide-vue-next";

const { t } = useI18n();
const router = useRouter();

interface ToolCard {
    path: string;
    nameKey: string;
    icon: any;
    descKey: string;
    ready: boolean;
}

const tools: ToolCard[] = [
    {
        path: "/revolution",
        nameKey: "app.nav.revolution",
        icon: RefreshCw,
        descKey: "revolution.description",
        ready: true,
    },
    {
        path: "/matrix",
        nameKey: "app.nav.matrix",
        icon: Calculator,
        descKey: "",
        ready: false,
    },
    {
        path: "/graphing",
        nameKey: "app.nav.graphing",
        icon: LineChart,
        descKey: "",
        ready: false,
    },
    {
        path: "/derivatives",
        nameKey: "app.nav.derivatives",
        icon: FunctionSquare,
        descKey: "",
        ready: false,
    },
    {
        path: "/geometry",
        nameKey: "app.nav.geometry",
        icon: Ruler,
        descKey: "",
        ready: false,
    },
    {
        path: "/statistics",
        nameKey: "app.nav.statistics",
        icon: BarChart3,
        descKey: "",
        ready: false,
    },
];

function goTo(tool: ToolCard) {
    router.push(tool.path);
}
</script>

<template>
    <div class="flex-1 max-w-[1100px] mx-auto px-6 pb-16 w-full">
        <!-- Hero -->
        <section
            class="relative py-20 max-md:py-12 text-center overflow-hidden"
        >
            <!-- Background blobs -->
            <div class="absolute inset-0 pointer-events-none overflow-hidden">
                <div
                    class="hero-circle absolute w-[400px] h-[400px] bg-primary rounded-full opacity-12 blur-[60px] -top-[120px] -left-[80px] animate-float"
                ></div>
                <div
                    class="hero-circle absolute w-[300px] h-[300px] bg-accent rounded-full opacity-12 blur-[60px] -top-[40px] -right-[60px] animate-float-reverse"
                ></div>
                <div
                    class="hero-circle absolute w-[200px] h-[200px] bg-success rounded-full opacity-12 blur-[60px] -bottom-[40px] left-[40%] animate-float-delayed"
                ></div>
            </div>

            <div class="relative z-[1]">
                <h1
                    class="text-[2.8rem] max-md:text-[2rem] font-extrabold tracking-tight leading-[1.15] mb-4 hero-title-gradient"
                >
                    {{ t("home.hero") }}
                </h1>
                <p
                    class="text-[1.1rem] max-md:text-[0.95rem] text-text-soft max-w-[540px] mx-auto mb-8 leading-relaxed"
                >
                    {{ t("home.heroDesc") }}
                </p>
                <button
                    class="btn btn-primary px-7 py-3 text-base gap-2.5"
                    @click="goTo(tools[0]!)"
                >
                    <span>{{ t("app.nav.revolution") }}</span>
                    <ArrowRight :size="16" />
                </button>
            </div>
        </section>

        <!-- Tools -->
        <section class="pt-4">
            <h2 class="text-[1.3rem] font-bold mb-6 text-text">
                {{ t("home.tools") }}
            </h2>
            <div
                class="grid grid-cols-[repeat(auto-fill,minmax(320px,1fr))] max-md:grid-cols-1 gap-4"
            >
                <div
                    v-for="tool in tools"
                    :key="tool.path"
                    class="card tool-card"
                    :class="{ 'tool-card--disabled': !tool.ready }"
                    @click="goTo(tool)"
                    role="button"
                    tabindex="0"
                    @keydown.enter="goTo(tool)"
                >
                    <div
                        class="flex items-center justify-center w-[52px] h-[52px] text-primary bg-bg rounded-md shrink-0"
                    >
                        <component :is="tool.icon" :size="24" />
                    </div>
                    <div class="flex-1 min-w-0">
                        <h3
                            class="text-[0.95rem] font-semibold text-text flex items-center gap-2.5 flex-wrap"
                        >
                            {{ t(tool.nameKey) }}
                            <span
                                v-if="!tool.ready"
                                class="badge badge-warning"
                            >
                                {{ t("home.comingSoon") }}
                            </span>
                        </h3>
                        <p
                            v-if="tool.descKey && tool.ready"
                            class="text-[0.82rem] text-text-soft mt-1 leading-normal line-clamp-2"
                        >
                            {{ t(tool.descKey) }}
                        </p>
                    </div>
                    <div class="tool-card__arrow text-text-muted shrink-0">
                        <ChevronRight :size="18" />
                    </div>
                </div>
            </div>
        </section>
    </div>
</template>

<style scoped>
@reference "../style.css";

/* --- Hero gradient title --- */
.hero-title-gradient {
    background: linear-gradient(
        135deg,
        var(--c-text) 0%,
        var(--c-primary) 100%
    );
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

/* --- Float animations --- */
@keyframes float {
    0%,
    100% {
        transform: translate(0, 0) scale(1);
    }
    33% {
        transform: translate(15px, -20px) scale(1.05);
    }
    66% {
        transform: translate(-10px, 10px) scale(0.97);
    }
}
.animate-float {
    animation: float 12s ease-in-out infinite;
}
.animate-float-reverse {
    animation: float 15s ease-in-out infinite reverse;
}
.animate-float-delayed {
    animation: float 10s ease-in-out infinite 2s;
}

/* --- Opacity helper (Tailwind v4 doesn't have opacity-12 by default) --- */
.opacity-12 {
    opacity: 0.12;
}

/* --- Tool cards --- */
.tool-card {
    @apply flex items-center gap-4 px-6 py-5 cursor-pointer select-none
           transition-all duration-200 ease-in-out;
}
.tool-card:hover {
    @apply border-primary-border shadow-md;
    transform: translateY(-2px);
}
.tool-card:active {
    transform: translateY(0);
}
.tool-card--disabled {
    @apply opacity-60 cursor-default;
}
.tool-card--disabled:hover {
    @apply border-border shadow-card;
    transform: none;
}
.tool-card__arrow {
    transition: transform 0.2s ease;
}
.tool-card:hover .tool-card__arrow {
    transform: translateX(3px);
    @apply text-primary;
}
</style>
